### ISSUE TITLE
关于注解类使用@Target(ElementType.METHOD)

### ISSUE THREAD

**Issue by sev7e0** [TaXueWWL/shleld-ratelimter#2]
在注解类中使用`@Target(ElementType.METHOD)`是否还需要在 handler 中写如下代码
```
Signature signature = proceedingJoinPoint.getSignature();
        if (!(signature instanceof MethodSignature)) {
            throw new IllegalArgumentException("the Annotation @RateLimter must used on method!");
        }
```

**Comment by TaXueWWL** [comment]
> MethodSignature

多谢建议，可以提一个pull request

**Comment by TaXueWWL** [comment]
> 在注解类中使用`@Target(ElementType.METHOD)`是否还需要在 handler 中写如下代码
> 
> ```
> Signature signature = proceedingJoinPoint.getSignature();
>         if (!(signature instanceof MethodSignature)) {
>             throw new IllegalArgumentException("the Annotation @RateLimter must used on method!");
>         }
> ```

当然是有必要的，如果不加的话，用在了非方法上，比如类上，没有效果，影响业务执行。
因此添加该注释，目的是在开发测试阶段就提示开发者使用到正确的位置，这里采用了fast-fail思想，希望能对你有所帮助。
