### ISSUE TITLE
redisTemplate 执行LUA脚本问题

### ISSUE THREAD

**Issue by lingjies** [TaXueWWL/shleld-ratelimter#3]
提一个小的优化
示例代码里，redisTemplate.execute(getRedisScript, keyList, expireTime, limitTimes); 这一句当Redis是集群模式直接抛出不支持执行脚本异常。

此处拿到原redis的connection执行脚本

**Comment by TaXueWWL** [comment]
> 脚本

辛苦提一个PR吧，多谢
